#!/bin/bash
set -euo pipefail
VAULT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
INDEX="$VAULT_DIR/06_Metadata/index.md"
TMPINDEX="$INDEX.tmp"

# Always regenerate frontmatter (index body is fully derived)
cat > "$TMPINDEX" << EOF
---
title: "Vault Index"
type: meta
tags:
  - meta
updated: $(date '+%Y-%m-%d')
---
EOF

echo "" >> "$TMPINDEX"
echo "> Auto-generated by rebuild-index.sh on $(date '+%Y-%m-%d %H:%M')" >> "$TMPINDEX"
echo "" >> "$TMPINDEX"

for dir in 00_Inbox 01_Projects 02_Areas 03_Resources 04_Archive 06_Metadata/Reference; do
  if [ -d "$VAULT_DIR/$dir" ]; then
    count=$(find "$VAULT_DIR/$dir" -name "*.md" -type f | wc -l | tr -d ' ')
    echo "## ${dir} ($count)" >> "$TMPINDEX"
    echo "" >> "$TMPINDEX"
    find "$VAULT_DIR/$dir" -name "*.md" -type f | sort | while read -r f; do
      name="$(basename "$f" .md)"
      echo "- [[$name]]" >> "$TMPINDEX"
    done
    echo "" >> "$TMPINDEX"
  fi
done

mv "$TMPINDEX" "$INDEX"
echo "Index rebuilt: $INDEX"
